name: Deploy

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: ngspa # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "./dist" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "12.x" # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install, test and build
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm install
          # npm run test --if-present
          npm run build --if-present
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

      # AZURE
      - name: "Deploy to Azure"
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # FIREBASE
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # SURGE
      - name: Deploy to Surge
        run: npm install -g surge
        run: surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      # GITHUB PAGES
      - name: Deploy to Github Pages
        run: npm run build -- --output-path build --base-href /angularspa/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build
