name: Surge

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to Surge
    steps:
      - uses: actions/checkout@v1
      - name: Install and deploy on Surge
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g surge
      - run: npm install
      - run: npm run build
      - run: surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
